[package]
name = "bitcoin-seed"
version = "0.0.1"
authors = ["Justin Moon <mail@justinmoon.com>"]
edition = "2018"

[dependencies]
bitcoin = { git = "https://github.com/rust-bitcoin/rust-bitcoin", branch = "master" }
log = "0.4"
env_logger = "0.6.1"

